# Generated by Django 5.0.2 on 2024-02-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Makale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yazar", models.TextField()),
                ("baslik", models.TextField()),
                ("aciklama", models.TextField()),
                ("metin", models.TextField()),
                ("sehir", models.TextField()),
                ("yayinlanma_tarihi", models.DateField()),
                ("aktif", models.BooleanField(default=True)),
                ("yaratilma_tarihi", models.DateField(auto_now_add=True)),
                ("güncellenme_tarihi", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
